name: Electron Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [20.x]
        include:
          - os: ubuntu-latest
            artifact-name: linux
          - os: macos-latest
            artifact-name: mac
          - os: windows-latest
            artifact-name: win

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build

    - name: Compile Electron
      run: npm run electron:compile

    - name: Build Electron app
      run: npm run electron:build
      env:
        CI: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pandora-client-${{ matrix.artifact-name }}-${{ github.sha }}
        path: |
          dist/*.AppImage
          dist/*.dmg
          dist/*.exe
          dist/*.zip
          dist/*.blockmap
          dist/*.yml
